name: VoiceAgent
options:
  bundleIdPrefix: com.voiceagent
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  VoiceAgent:
    type: application
    platform: iOS
    sources:
      - VoiceAgent
    settings:
      base:
        INFOPLIST_FILE: VoiceAgent/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.voiceagent.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_TEAM: ""
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: VoiceAgent/Resources/Info.plist
      properties:
        NSMicrophoneUsageDescription: "VoiceAgent needs microphone access to capture your voice for the voice assistant."
        UILaunchScreen: {}

  VoiceAgentTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - VoiceAgentTests
    dependencies:
      - target: VoiceAgent
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.voiceagent.tests
